<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('nationalities')->truncate();
        DB::table('nationalities')->insert([
            ['name_en' => 'Afghan', 'name_ar' => 'أفغاني'],
            ['name_en' => 'Albanian', 'name_ar' => 'ألباني'],
            ['name_en' => 'Algerian', 'name_ar' => 'جزائري'],
            ['name_en' => 'American', 'name_ar' => 'أمريكي'],
            ['name_en' => 'Andorran', 'name_ar' => 'أندوري'],
            ['name_en' => 'Angolan', 'name_ar' => 'أنغولي'],
            ['name_en' => 'Argentine', 'name_ar' => 'أرجنتيني'],
            ['name_en' => 'Armenian', 'name_ar' => 'أرميني'],
            ['name_en' => 'Australian', 'name_ar' => 'أسترالي'],
            ['name_en' => 'Austrian', 'name_ar' => 'نمساوي'],
            ['name_en' => 'Azerbaijani', 'name_ar' => 'أذربيجاني'],
            ['name_en' => 'Bahraini', 'name_ar' => 'بحريني'],
            ['name_en' => 'Bangladeshi', 'name_ar' => 'بنغلاديشي'],
            ['name_en' => 'Barbadian', 'name_ar' => 'بربادوسي'],
            ['name_en' => 'Belarusian', 'name_ar' => 'بيلاروسي'],
            ['name_en' => 'Belgian', 'name_ar' => 'بلجيكي'],
            ['name_en' => 'Beninese', 'name_ar' => 'بنيني'],
            ['name_en' => 'Bhutanese', 'name_ar' => 'بوتاني'],
            ['name_en' => 'Bolivian', 'name_ar' => 'بوليفي'],
            ['name_en' => 'Bosnian', 'name_ar' => 'بوسني'],
            ['name_en' => 'Botswanan', 'name_ar' => 'بوتسواني'],
            ['name_en' => 'Brazilian', 'name_ar' => 'برازيلي'],
            ['name_en' => 'British', 'name_ar' => 'بريطاني'],
            ['name_en' => 'Bulgarian', 'name_ar' => 'بلغاري'],
            ['name_en' => 'Burmese', 'name_ar' => 'بورمي'],
            ['name_en' => 'Cambodian', 'name_ar' => 'كمبودي'],
            ['name_en' => 'Cameroonian', 'name_ar' => 'كاميروني'],
            ['name_en' => 'Canadian', 'name_ar' => 'كندي'],
            ['name_en' => 'Chadian', 'name_ar' => 'تشادي'],
            ['name_en' => 'Chilean', 'name_ar' => 'شيلي'],
            ['name_en' => 'Chinese', 'name_ar' => 'صيني'],
            ['name_en' => 'Colombian', 'name_ar' => 'كولومبي'],
            ['name_en' => 'Congolese', 'name_ar' => 'كونغولي'],
            ['name_en' => 'Croatian', 'name_ar' => 'كرواتي'],
            ['name_en' => 'Cuban', 'name_ar' => 'كوبي'],
            ['name_en' => 'Cypriot', 'name_ar' => 'قبرصي'],
            ['name_en' => 'Czech', 'name_ar' => 'تشيكي'],
            ['name_en' => 'Danish', 'name_ar' => 'دنماركي'],
            ['name_en' => 'Djiboutian', 'name_ar' => 'جيبوتي'],
            ['name_en' => 'Dominican', 'name_ar' => 'دومينيكاني'],
            ['name_en' => 'Dutch', 'name_ar' => 'هولندي'],
            ['name_en' => 'Ecuadorian', 'name_ar' => 'إكوادوري'],
            ['name_en' => 'Egyptian', 'name_ar' => 'مصري'],
            ['name_en' => 'Emirati', 'name_ar' => 'إماراتي'],
            ['name_en' => 'Estonian', 'name_ar' => 'إستوني'],
            ['name_en' => 'Ethiopian', 'name_ar' => 'إثيوبي'],
            ['name_en' => 'Finnish', 'name_ar' => 'فنلندي'],
            ['name_en' => 'French', 'name_ar' => 'فرنسي'],
            ['name_en' => 'Georgian', 'name_ar' => 'جورجي'],
            ['name_en' => 'German', 'name_ar' => 'ألماني'],
            ['name_en' => 'Ghanaian', 'name_ar' => 'غاني'],
            ['name_en' => 'Greek', 'name_ar' => 'يوناني'],
            ['name_en' => 'Guatemalan', 'name_ar' => 'غواتيمالي'],
            ['name_en' => 'Guinean', 'name_ar' => 'غيني'],
            ['name_en' => 'Haitian', 'name_ar' => 'هايتي'],
            ['name_en' => 'Honduran', 'name_ar' => 'هندوراسي'],
            ['name_en' => 'Hungarian', 'name_ar' => 'هنغاري'],
            ['name_en' => 'Icelandic', 'name_ar' => 'آيسلندي'],
            ['name_en' => 'Indian', 'name_ar' => 'هندي'],
            ['name_en' => 'Indonesian', 'name_ar' => 'إندونيسي'],
            ['name_en' => 'Iranian', 'name_ar' => 'إيراني'],
            ['name_en' => 'Iraqi', 'name_ar' => 'عراقي'],
            ['name_en' => 'Irish', 'name_ar' => 'أيرلندي'],
            ['name_en' => 'Israeli', 'name_ar' => 'إسرائيلي'],
            ['name_en' => 'Italian', 'name_ar' => 'إيطالي'],
            ['name_en' => 'Japanese', 'name_ar' => 'ياباني'],
            ['name_en' => 'Jordanian', 'name_ar' => 'أردني'],
            ['name_en' => 'Kazakh', 'name_ar' => 'كازاخي'],
            ['name_en' => 'Kenyan', 'name_ar' => 'كيني'],
            ['name_en' => 'Kuwaiti', 'name_ar' => 'كويتي'],
            ['name_en' => 'Kyrgyz', 'name_ar' => 'قيرغيزي'],
            ['name_en' => 'Laotian', 'name_ar' => 'لاوسي'],
            ['name_en' => 'Latvian', 'name_ar' => 'لاتفي'],
            ['name_en' => 'Lebanese', 'name_ar' => 'لبناني'],
            ['name_en' => 'Liberian', 'name_ar' => 'ليبيري'],
            ['name_en' => 'Libyan', 'name_ar' => 'ليبي'],
            ['name_en' => 'Lithuanian', 'name_ar' => 'ليتواني'],
            ['name_en' => 'Luxembourgish', 'name_ar' => 'لوكسمبورغي'],
            ['name_en' => 'Macedonian', 'name_ar' => 'مقدوني'],
            ['name_en' => 'Madagascan', 'name_ar' => 'مدغشقري'],
            ['name_en' => 'Malagasy', 'name_ar' => 'مدغشقري'],
            ['name_en' => 'Malaysian', 'name_ar' => 'ماليزي'],
            ['name_en' => 'Maldivian', 'name_ar' => 'مالديفي'],
            ['name_en' => 'Malian', 'name_ar' => 'مالي'],
            ['name_en' => 'Maltese', 'name_ar' => 'مالطي'],
            ['name_en' => 'Mauritanian', 'name_ar' => 'موريتاني'],
            ['name_en' => 'Mexican', 'name_ar' => 'مكسيكي'],
            ['name_en' => 'Mongolian', 'name_ar' => 'منغولي'],
            ['name_en' => 'Moroccan', 'name_ar' => 'مغربي'],
            ['name_en' => 'Mozambican', 'name_ar' => 'موزمبيقي'],
            ['name_en' => 'Namibian', 'name_ar' => 'ناميبي'],
            ['name_en' => 'Nepalese', 'name_ar' => 'نيبالي'],
            ['name_en' => 'New Zealander', 'name_ar' => 'نيوزيلندي'],
            ['name_en' => 'Nicaraguan', 'name_ar' => 'نيكاراغوي'],
            ['name_en' => 'Nigerian', 'name_ar' => 'نيجيري'],
            ['name_en' => 'North Korean', 'name_ar' => 'كوري شمالي'],
            ['name_en' => 'Norwegian', 'name_ar' => 'نرويجي'],
            ['name_en' => 'Omani', 'name_ar' => 'عماني'],
            ['name_en' => 'Pakistani', 'name_ar' => 'باكستاني'],
            ['name_en' => 'Palestinian', 'name_ar' => 'فلسطيني'],
            ['name_en' => 'Panamanian', 'name_ar' => 'بنمي'],
            ['name_en' => 'Papua New Guinean', 'name_ar' => 'بابوا غيني'],
            ['name_en' => 'Paraguayan', 'name_ar' => 'باراغواي'],
            ['name_en' => 'Peruvian', 'name_ar' => 'بيروفي'],
            ['name_en' => 'Philippine', 'name_ar' => 'فلبيني'],
            ['name_en' => 'Polish', 'name_ar' => 'بولندي'],
            ['name_en' => 'Portuguese', 'name_ar' => 'برتغالي'],
            ['name_en' => 'Qatari', 'name_ar' => 'قطري'],
            ['name_en' => 'Romanian', 'name_ar' => 'روماني'],
            ['name_en' => 'Russian', 'name_ar' => 'روسي'],
            ['name_en' => 'Rwandan', 'name_ar' => 'رواندي'],
            ['name_en' => 'Saudi', 'name_ar' => 'سعودي'],
            ['name_en' => 'Senegalese', 'name_ar' => 'سنغالي'],
            ['name_en' => 'Serbian', 'name_ar' => 'صربي'],
            ['name_en' => 'Singaporean', 'name_ar' => 'سنغافوري'],
            ['name_en' => 'Slovak', 'name_ar' => 'سلوفاكي'],
            ['name_en' => 'Slovenian', 'name_ar' => 'سلوفيني'],
            ['name_en' => 'Somali', 'name_ar' => 'صومالي'],
            ['name_en' => 'South African', 'name_ar' => 'جنوب أفريقي'],
            ['name_en' => 'South Korean', 'name_ar' => 'كوري جنوبي'],
            ['name_en' => 'Spanish', 'name_ar' => 'إسباني'],
            ['name_en' => 'Sri Lankan', 'name_ar' => 'سريلانكي'],
            ['name_en' => 'Sudanese', 'name_ar' => 'سوداني'],
            ['name_en' => 'Swazi', 'name_ar' => 'سوازي'],
            ['name_en' => 'Swedish', 'name_ar' => 'سويدي'],
            ['name_en' => 'Swiss', 'name_ar' => 'سويسري'],
            ['name_en' => 'Syrian', 'name_ar' => 'سوري'],
            ['name_en' => 'Tajik', 'name_ar' => 'طاجيكي'],
            ['name_en' => 'Tanzanian', 'name_ar' => 'تنزاني'],
            ['name_en' => 'Thai', 'name_ar' => 'تايلندي'],
            ['name_en' => 'Togolese', 'name_ar' => 'توغولي'],
            ['name_en' => 'Tunisian', 'name_ar' => 'تونسي'],
            ['name_en' => 'Turkish', 'name_ar' => 'تركي'],
            ['name_en' => 'Turkmen', 'name_ar' => 'تركماني'],
            ['name_en' => 'Ugandan', 'name_ar' => 'أوغندي'],
            ['name_en' => 'Ukrainian', 'name_ar' => 'أوكراني'],
            ['name_en' => 'Uruguayan', 'name_ar' => 'أوروغواي'],
            ['name_en' => 'Uzbek', 'name_ar' => 'أوزبكي'],
            ['name_en' => 'Venezuelan', 'name_ar' => 'فنزويلي'],
            ['name_en' => 'Vietnamese', 'name_ar' => 'فيتنامي'],
            ['name_en' => 'Yemeni', 'name_ar' => 'يمني'],
            ['name_en' => 'Zambian', 'name_ar' => 'زامبي'],
            ['name_en' => 'Zimbabwean', 'name_ar' => 'زيمبابوي'],
        ]);
    }
}
