<?php


namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class SpecializationsSeeder extends Seeder
{
    public function run()
    {
        DB::table('specializations')->truncate();
        DB::table('specializations')->insert([
            ['name_en' => 'Medicine', 'name_ar' => 'طب'],
            ['name_en' => 'Dentistry', 'name_ar' => 'طب أسنان'],
            ['name_en' => 'Pharmacy', 'name_ar' => 'صيدلة'],
            ['name_en' => 'Doctor of Pharmacy', 'name_ar' => 'دكتور صيدلة'],
            ['name_en' => 'Civil Engineering', 'name_ar' => 'هندسة مدنية'],
            ['name_en' => 'Electrical Engineering', 'name_ar' => 'هندسة كهربائية'],
            ['name_en' => 'Mechanical Engineering', 'name_ar' => 'هندسة ميكانيكية'],
            ['name_en' => 'Chemical Engineering', 'name_ar' => 'هندسة كيميائية'],
            ['name_en' => 'Industrial Engineering', 'name_ar' => 'هندسة صناعية'],
            ['name_en' => 'Computer Engineering', 'name_ar' => 'هندسة حاسوب'],
            ['name_en' => 'Mechatronics Engineering', 'name_ar' => 'هندسة ميكاترونيكس'],
            ['name_en' => 'Telecommunications Engineering', 'name_ar' => 'هندسة اتصالات'],
            ['name_en' => 'Electronics Engineering', 'name_ar' => 'هندسة الكترونيات'],
            ['name_en' => 'Renewable Energy Engineering', 'name_ar' => 'هندسة طاقة متجددة'],
            ['name_en' => 'Nursing', 'name_ar' => 'تمريض'],
            ['name_en' => 'Computer Science', 'name_ar' => 'علم الحاسوب'],
            ['name_en' => 'Management Information Systems', 'name_ar' => 'نظم معلومات ادارية'],
            ['name_en' => 'Computer Information Systems', 'name_ar' => 'نظم معلومات حاسوبية'],
            ['name_en' => 'Accounting Information Systems', 'name_ar' => 'نظم معلومات محاسبية'],
            ['name_en' => 'Software Engineering', 'name_ar' => 'هندسة برمجيات'],
            ['name_en' => 'Computer Networks Systems', 'name_ar' => 'نظم شبكات الحاسوب'],
            ['name_en' => 'Mathematics', 'name_ar' => 'رياضيات'],
            ['name_en' => 'Physics', 'name_ar' => 'فيزياء'],
            ['name_en' => 'Chemistry', 'name_ar' => 'كيمياء'],
            ['name_en' => 'Biological Sciences', 'name_ar' => 'علوم حياتية'],
            ['name_en' => 'Environmental Geology', 'name_ar' => 'جيولوجيا بيئية'],
            ['name_en' => 'Medical Laboratory Sciences', 'name_ar' => 'علوم طبية مخبرية'],
            ['name_en' => 'Nutrition', 'name_ar' => 'تغذية'],
            ['name_en' => 'Economics', 'name_ar' => 'اقتصاد'],
            ['name_en' => 'Business Administration', 'name_ar' => 'ادارة اعمال'],
            ['name_en' => 'Accounting', 'name_ar' => 'محاسبة'],
            ['name_en' => 'Marketing', 'name_ar' => 'تسويق'],
            ['name_en' => 'Public Administration', 'name_ar' => 'ادارة عامة'],
            ['name_en' => 'English Language', 'name_ar' => 'لغة انجليزية'],
            ['name_en' => 'Arabic Language', 'name_ar' => 'لغة عربية'],
            ['name_en' => 'History', 'name_ar' => 'تاريخ'],
            ['name_en' => 'Geography', 'name_ar' => 'جغرافيا'],
            ['name_en' => 'Philosophy', 'name_ar' => 'فلسفة'],
            ['name_en' => 'Law', 'name_ar' => 'قانون'],
            ['name_en' => 'Psychology', 'name_ar' => 'علم نفس'],
            ['name_en' => 'Sociology', 'name_ar' => 'علم اجتماع'],
            ['name_en' => 'Political Science', 'name_ar' => 'علوم سياسية'],
            ['name_en' => 'Primary Teacher', 'name_ar' => 'معلم صف'],
            ['name_en' => 'Special Education', 'name_ar' => 'تربية خاصة'],
            ['name_en' => 'Child Education', 'name_ar' => 'تربية طفل'],
            ['name_en' => 'Counseling and Mental Health', 'name_ar' => 'إرشاد وصحة نفسية'],
            ['name_en' => 'Library Science', 'name_ar' => 'علم مكتبات'],
            ['name_en' => 'Islamic Jurisprudence and its Foundations', 'name_ar' => 'الفقه وأصوله'],
            ['name_en' => 'Islamic Banks', 'name_ar' => 'مصارف إسلامية'],
            ['name_en' => 'Tourism and Archaeology', 'name_ar' => 'سياحة وآثار'],
            ['name_en' => 'Physical Education', 'name_ar' => 'تربية رياضية'],
            ['name_en' => 'Risk Management and Insurance', 'name_ar' => 'إدارة المخاطر والتأمين'],
            ['name_en' => 'Hotel Management', 'name_ar' => 'إدارة فندقة'],
            ['name_en' => 'Translation', 'name_ar' => 'ترجمة'],
            ['name_en' => 'Journalism and Media', 'name_ar' => 'صحافة وإعلام'],
            ['name_en' => 'Public Relations', 'name_ar' => 'علاقات عامة'],
            ['name_en' => 'Finance and Banking', 'name_ar' => 'علوم مالية ومصرفية'],
            ['name_en' => 'Technological Engineering', 'name_ar' => 'هندسة تكنولوجية'],
            ['name_en' => 'Educational Leadership and Management', 'name_ar' => 'إدارة وقيادة تربوية'],
            ['name_en' => 'Interior Design', 'name_ar' => 'تصميم داخلي'],
            ['name_en' => 'Art Education', 'name_ar' => 'تربية فنية'],
            ['name_en' => 'Vocational Education', 'name_ar' => 'تربية مهنية'],
            ['name_en' => 'Human Resources', 'name_ar' => 'موارد بشرية'],
            ['name_en' => 'Developmental Resources', 'name_ar' => 'موارد تنموية'],
            ['name_en' => 'Graphic Design', 'name_ar' => 'جرافيك ديزاين'],
            ['name_en' => 'Anthropology', 'name_ar' => 'الانثروبولوجية'],
            ['name_en' => 'International Relations', 'name_ar' => 'علاقات دولية'],
            ['name_en' => 'Biomedical Engineering', 'name_ar' => 'هندسة طبية وحيوية'],
            ['name_en' => 'Agricultural Engineering', 'name_ar' => 'هندسة زراعية'],
            ['name_en' => 'Water and Environmental Management', 'name_ar' => 'ادارة مياه وبيئة'],
            ['name_en' => 'Plant Production', 'name_ar' => 'انتاج نباتي'],
            ['name_en' => 'Animal Production', 'name_ar' => 'انتاج حيواني'],
            ['name_en' => 'Secretary', 'name_ar' => 'سكرتاريا'],
            ['name_en' => 'Network Engineering', 'name_ar' => 'هندسة شبكات'],
            ['name_en' => 'Business Economics', 'name_ar' => 'اقتصاد مال واعمال'],
            ['name_en' => 'Strategic Studies', 'name_ar' => 'دراسات استراتيجية'],
            ['name_en' => 'Teaching Methods', 'name_ar' => 'أساليب تدريس'],
            ['name_en' => 'Applied Sciences', 'name_ar' => 'علوم تطبيقية'],
            ['name_en' => 'Political Studies', 'name_ar' => 'سياسة'],
            ['name_en' => 'Information and Communication Technology', 'name_ar' => 'تكنولوجيا معلومات واتصالات'],
            ['name_en' => 'Educational Administration', 'name_ar' => 'ادارة تربوية'],
            ['name_en' => 'Tourism Guidance', 'name_ar' => 'ارشاد سياحي'],
            ['name_en' => 'Curricula and Teaching', 'name_ar' => 'مناهج وتدريس'],
            ['name_en' => 'Linguistic and Grammatical Studies', 'name_ar' => 'دراسات لغوية ونحوية'],
            ['name_en' => 'Rights', 'name_ar' => 'حقوق'],
            ['name_en' => 'Educational Qualification', 'name_ar' => 'تأهيل تربوي'],
            ['name_en' => 'Information Technology in Education', 'name_ar' => 'تكنولوجيا المعلومات في التربية'],
            ['name_en' => 'Family Counseling', 'name_ar' => 'ارشاد اسري'],
            ['name_en' => 'Sharia and its Principles', 'name_ar' => 'شريعة وأصول دين'],
            ['name_en' => 'Islamic Education', 'name_ar' => 'تربية إسلامية'],
            ['name_en' => 'First Jurisprudence Texts', 'name_ar' => 'المتون الفقيه الأولى'],
            ['name_en' => 'Special Education', 'name_ar' => 'تربية خاصة'],
            ['name_en' => 'Primary Education', 'name_ar' => 'تعليم ابتدائي'],
            ['name_en' => 'French Language', 'name_ar' => 'لغة فرنسية'],
            ['name_en' => 'Aviation Engineering', 'name_ar' => 'هندسة طيران'],
            ['name_en' => 'Educational Sciences', 'name_ar' => 'علوم تربوية'],
            ['name_en' => 'Islamic Sciences and Civilization', 'name_ar' => 'علوم شرعية وحضارة'],
            ['name_en' => 'Educational Leadership and Management', 'name_ar' => 'إدارة وقيادة تربوية'],
            ['name_en' => 'Architectural Engineering', 'name_ar' => 'هندسة معمارية'],
            ['name_en' => 'Conservation of Antiquities', 'name_ar' => 'المحافظة على الآثار'],
            ['name_en' => 'Nuclear Physics', 'name_ar' => 'فيزياء نووية'],
            ['name_en' => 'Music', 'name_ar' => 'موسيقى'],
            ['name_en' => 'Social Studies', 'name_ar' => 'اجتماعيات'],
            ['name_en' => 'Visual Arts', 'name_ar' => 'فنون بصرية'],
            ['name_en' => 'Medical Analysis', 'name_ar' => 'تحاليل طبية'],
            ['name_en' => 'School Administration', 'name_ar' => 'الادارة المدرسية'],
            ['name_en' => 'Educational Administration', 'name_ar' => 'الإدارة التربوية'],
            ['name_en' => 'Business Administration', 'name_ar' => 'ادارة اعمال'],
            ['name_en' => 'Education', 'name_ar' => 'التربية'],
            ['name_en' => 'Office Management', 'name_ar' => 'ادارة مكاتب'],
            ['name_en' => 'Audiology and Speech', 'name_ar' => 'السمع والنطق'],
            ['name_en' => 'Technology and Communication', 'name_ar' => 'تكنولوجيا واتصال'],
            ['name_en' => 'Islamic Sciences and Civilization', 'name_ar' => 'علوم شرعية وحضارة'],
        ]);
    }
}
